[fast-reboot][cosmetic] Fixed debug/error prints with the correct reboot type
Signed-off-by: Yair Raviv <yraviv@nvidia.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -57,7 +57,7 @@ EXIT_LEFTOVER_CPA_TUNNEL=30
 function error()
 {
     echo $@ >&2
-    logger -p user.err "Error seen during warm-reboot shutdown process: $@"
+    logger -p user.err "Error seen during $REBOOT_SCRIPT_NAME shutdown process: $@"
 }
 
 function debug()
@@ -147,7 +147,7 @@ function parseOptions()
 function clear_boot()
 {
     # common_clear
-    debug "${REBOOT_TYPE} failure ($?) cleanup ..."
+    debug "${REBOOT_SCRIPT_NAME} failure ($?) cleanup ..."
 
     /sbin/kexec -u -a || /bin/true
 
@@ -520,9 +520,9 @@ function check_pfc_storm_active()
     debug "Checking for active PFC storms..."
     
     if pfcwd show stats --check-storm >/dev/null 2>&1; then
-        debug "No active PFC storms detected. Safe to proceed with warm-reboot..."
+        debug "No active PFC storms detected. Safe to proceed with $REBOOT_SCRIPT_NAME..."
     else
-        error "PFC storm detected. Aborting warm-reboot to prevent failure in recovery path..."
+        error "PFC storm detected. Aborting $REBOOT_SCRIPT_NAME to prevent failure in recovery path..."
         exit ${EXIT_PFC_STORM_DETECTED}
     fi
 }
